### PR TITLE
Add Librewolf icons + Bitwig Studio MIME file icons

### PR DESCRIPTION
**Pull request by yioannides**
Duplicate merge request from [somepaulo's MoreWaita](https://github.com/somepaulo/MoreWaita/pull/164).

Notice: As I mentioned in the original merge request, I don't know how to assign file types to apps (if you can let me know how, I'd really appreciate it!), but as I mentioned in my open issue, it affects the following file types: `.bwproject` `.bwpreset` `.bwclip` `.multisample`

- [x] associate the new mime file icons to the file types in `mimes/scalable/meson.build`

### CODE REVIEW

**Comment by iaacornus** [comment]
yes, I know how to add/associate them with app. I'll create a TODO so I can deal with it later after I got home. If you plan to do it yourself, you can edit the file in `mimes/scalable/meson.build` and `apps/scalable/meson.build` and include the app and associate those files.

**Review by iaacornus — APPROVED** [review]
it seems like you already associated the icon of librewolf, the only left is the mimetypes. You can simply add the svgs into `mime/scalable/meson.build` to associate the mime icons with the files.

**Comment by yioannides** [comment]
Could you please check whether I did it correctly? (sorry, this is my very first merge request on Github)

**Review by iaacornus — APPROVED** [review]
looks good to me, i'll test it on my system and see if it works later since i dont have bitwig and bitwig files yet

**Comment by iaacornus** [comment]
hi. I apologize, I just got free. Does this look right?
image
I don't have any more test image or not sure what type of file it should be associate to, but i got a sample from the internet

**Comment by yioannides** [comment]
Yes, that's looks right! As I said above, the files associated with this icon are: `.bwproject` `.bwpreset` `.bwclip` `.multisample`

**Comment by iaacornus** [comment]
can you redirect the pull to bitwig branch? i'll further add more links to associate it with more files and mimes

**Comment by iaacornus** [comment]
it seems there's also mimetypes called templates, project folder and etc, it would be better if we can also account for that

**Comment by iaacornus** [comment]
thank you for this contribution @yioannides, I'll sync the main repo later after I added/associated more mimetypes later so those who uses git version can sync with the changes immediately. Cheers!

**Pull request merged**
